/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bprakash' at '8/30/19 4:31 PM' with Gradle 2.6
 *
 * @author bprakash, @date 8/30/19 4:31 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
